<?xml version="1.0" encoding="utf-8"?><Database Name="DBBILUXURY" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-4H2CDN2\LENAM1999;Initial Catalog=DBBILUXURY;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DBBILUXURYConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETDONHANG" Member="CHITIETDONHANGs">
    <Type Name="CHITIETDONHANG">
      <Column Name="MaChiTietDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DONHANG_CHITIETDONHANG" Member="DONHANG" ThisKey="MaDH" OtherKey="MaDH" Type="DONHANG" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETDONHANG" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CONTACT" Member="CONTACTs">
    <Type Name="CONTACT">
      <Column Name="ConTactID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ConTent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DONHANG" Member="DONHANGs">
    <Type Name="DONHANG">
      <Column Name="MaDH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaShipper" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="DONHANG_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MaDH" OtherKey="MaDH" Type="CHITIETDONHANG" />
      <Association Name="KHACHHANG_DONHANG" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NHANVIEN_DONHANG" Member="NHANVIEN" ThisKey="MaNV" OtherKey="MaNV" Type="NHANVIEN" IsForeignKey="true" />
      <Association Name="SHIPPER_DONHANG" Member="SHIPPER" ThisKey="MaShipper" OtherKey="MaShipper" Type="SHIPPER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FEEDBACK" Member="FEEDBACKs">
    <Type Name="FEEDBACK">
      <Column Name="FeedbackID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_FEEDBACK" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOITHIEU" Member="GIOITHIEUs">
    <Type Name="GIOITHIEU">
      <Column Name="AboutID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IMAGE" Member="IMAGEs">
    <Type Name="IMAGE">
      <Column Name="ImageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LinkAnh" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaTinTuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_IMAGE" Member="KHACHHANG" ThisKey="MaKH" OtherKey="MaKH" Type="KHACHHANG" IsForeignKey="true" />
      <Association Name="NEW_IMAGE" Member="NEW" ThisKey="MaTinTuc" OtherKey="NewID" Type="NEW" IsForeignKey="true" />
      <Association Name="SANPHAM_IMAGE" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHACHHANG" Member="KHACHHANGs">
    <Type Name="KHACHHANG">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KHACHHANG_DONHANG" Member="DONHANGs" ThisKey="MaKH" OtherKey="MaKH" Type="DONHANG" />
      <Association Name="KHACHHANG_FEEDBACK" Member="FEEDBACKs" ThisKey="MaKH" OtherKey="MaKH" Type="FEEDBACK" />
      <Association Name="KHACHHANG_IMAGE" Member="IMAGEs" ThisKey="MaKH" OtherKey="MaKH" Type="IMAGE" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MieuTa" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="SANPHAMs" ThisKey="MaLoaiSP" OtherKey="MaLoaiSP" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NEWS" Member="NEWs">
    <Type Name="NEW">
      <Column Name="NewID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NewImage" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ViewCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NEW_IMAGE" Member="IMAGEs" ThisKey="NewID" OtherKey="MaTinTuc" Type="IMAGE" />
      <Association Name="SANPHAM_NEW" Member="SANPHAM" ThisKey="MaSP" OtherKey="MaSP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHACUNGCAP" Member="NHACUNGCAPs">
    <Type Name="NHACUNGCAP">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="SANPHAMs" ThisKey="MaNCC" OtherKey="MaNCC" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.Char" DbType="Char(1) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Account" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="NHANVIEN_DONHANG" Member="DONHANGs" ThisKey="MaNV" OtherKey="MaNV" Type="DONHANG" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ChatLieu" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="KieuDang" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="XuatXu" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="SANPHAM_CHITIETDONHANG" Member="CHITIETDONHANGs" ThisKey="MaSP" OtherKey="MaSP" Type="CHITIETDONHANG" />
      <Association Name="SANPHAM_IMAGE" Member="IMAGEs" ThisKey="MaSP" OtherKey="MaSP" Type="IMAGE" />
      <Association Name="SANPHAM_NEW" Member="NEWs" ThisKey="MaSP" OtherKey="MaSP" Type="NEW" />
      <Association Name="LOAISANPHAM_SANPHAM" Member="LOAISANPHAM" ThisKey="MaLoaiSP" OtherKey="MaLoaiSP" Type="LOAISANPHAM" IsForeignKey="true" />
      <Association Name="NHACUNGCAP_SANPHAM" Member="NHACUNGCAP" ThisKey="MaNCC" OtherKey="MaNCC" Type="NHACUNGCAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SHIPPER" Member="SHIPPERs">
    <Type Name="SHIPPER">
      <Column Name="MaShipper" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenShipper" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Association Name="SHIPPER_DONHANG" Member="DONHANGs" ThisKey="MaShipper" OtherKey="MaShipper" Type="DONHANG" />
    </Type>
  </Table>
  <Table Name="dbo.SIZE" Member="SIZEs">
    <Type Name="SIZE">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Size" Member="Size1" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>